FROM node:14 AS builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install
COPY . .

CMD [ "npm", "run", "build" ]

FROM nginx

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]