version: '3'
services:
  frontend:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'

  backend:
    restart: unless-stopped

  mongo:
    restart: unless-stopped
