version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  e2e:
    image: cypress
    build: ./frontend/e2e
    container_name: cypress
    depends_on:
      - frontend
    command: npx cypress run
    volumes:
      - ./frontend/e2e/cypress:/app/cypress
      - ./frontend/e2e/cypress.json:/app/cypress.json

  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
