version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - '80:80'

  backend:
    environment:
      NODE_ENV: production
