version: '3'
services:
  frontend:
    restart: always
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - JWT_TOKEN=${JWT_TOKEN}
      - MONGO_STORE_SECRET_KEY=${MONGO_STORE_SECRET_KEY}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PSW=${MONGO_PSW}
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PSW}
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-db:
