version: '3'
services:
  frontend:
    build:
      context: ./frontend
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    env_file:
      - ./backend/.env
    container_name: backend
    ports:
      - '5001:5001'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ./backend/.env
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-db:
    driver: local