version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  backend:
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
