/* Authentication */
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

/* Categories */
export const SET_CATEGORIES_LIST = 'SET_CATEGORIES_LIST';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SHOW_EDIT_CATEGORY = 'SHOW_EDIT_CATEGORY';
export const HIDE_EDIT_CATEGORY = 'HIDE_EDIT_CATEGORY';
export const SET_EDIT_CATEGORY_ERRORS = 'SET_EDIT_CATEGORY_ERRORS';

/* Resources */
export const SET_RESOURCES_LIST = 'SET_RESOURCES_LIST';
export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
