name: Backend unit testing

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          working-directory: ./backend
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Execute tests
        working-directory: ./backend
        run: |
          npm ci |
          npm run build --if-present |
          npm test
